const defaultTheme = require('tailwindcss/defaultTheme')

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dce3ec",
        "clay-purple-light": "#e4c1f9",
        "clay-purple-dark": "#b377dc",
        "on-surface-variant": "#3f4943",
        "inverse-surface": "#2a3138",
        "inverse-on-surface": "#ebf1fa",
        "dark-jewel-yellow": "#92400e",
        "surface-dim": "#d4dbe3",
        "clay-pink-dark": "#ff8fb3",
        "clay-yellow-light": "#fff4bd",
        "on-background": "#151c22",
        "clay-pink-light": "#ffc8dd",
        "on-tertiary-fixed": "#400013",
        "tertiary-container": "#ff98a8",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "dark-jewel-purple": "#5b21b6",
        "clay-green-main": "#b7e4c7",
        "primary-container": "#74c69d",
        "on-secondary-fixed": "#001d32",
        "on-primary-fixed-variant": "#005236",
        "clay-green-light": "#d8f3dc",
        "clay-purple-deep": "#7e5ca0",
        "background": "#f6f9ff",
        "clay-green-dark": "#74c69d",
        "surface-tint": "#0e6c4a",
        "clay-yellow-dark": "#ffcc77",
        "tertiary-fixed-dim": "#ffb2bc",
        "on-error": "#ffffff",
        "dark-jewel-green": "#065f46",
        "surface-bright": "#f6f9ff",
        "on-primary-container": "#005236",
        "secondary": "#30628a",
        "inverse-primary": "#85d7ad",
        "dark-jewel-blue": "#1e40af",
        "primary-fixed-dim": "#85d7ad",
        "tertiary-fixed": "#ffd9dd",
        "clay-blue-main": "#a2d2ff",
        "on-surface": "#151c22",
        "error": "#ba1a1a",
        "clay-blue-deep": "#356590",
        "on-tertiary-container": "#8d0f37",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#9bcbf8",
        "clay-yellow-deep": "#d4a373",
        "tertiary": "#ad2c4d",
        "on-tertiary-fixed-variant": "#8d0f36",
        "clay-pink-main": "#ffb3d9",
        "primary": "#0e6c4a",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#002113",
        "dark-jewel-pink": "#9d2d6d",
        "surface-container": "#e8eef7",
        "outline-variant": "#bec9c0",
        "secondary-container": "#a1d1fe",
        "secondary-fixed": "#cde5ff",
        "surface": "#f6f9ff",
        "clay-blue-light": "#cae9ff",
        "surface-container-highest": "#dce3ec",
        "outline": "#6f7a72",
        "clay-purple-main": "#d4a5f3",
        "clay-blue-dark": "#5a9fd4",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e2e9f1",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#265a81",
        "surface-container-low": "#eef4fd",
        "clay-green-deep": "#2d6a4f",
        "clay-pink-deep": "#ff6a88",
        "on-secondary-fixed-variant": "#104a70",
        "primary-fixed": "#a0f4c8",
        "clay-yellow-main": "#ffe6a7",
      },
      spacing: {
        'unit': '4px',
        'clay-padding-md': '20px 24px',
        'container-padding': '24px',
        'gutter': '16px',
        'stack-gap': '12px',
        'clay-padding-sm': '12px 16px',
      },
      fontSize: {
        'display-hero': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'tool-title': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '600' }],
        'micro': ['10px', { lineHeight: '1.2', fontWeight: '500' }],
        'display-hero-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      fontFamily: {
        sans: ['Inter', 'Nunito', 'Quicksand', ...defaultTheme.fontFamily.sans],
        mono: ['JetBrains Mono', ...defaultTheme.fontFamily.mono],
        'tool-title': ['Inter'],
        'label-md': ['Inter'],
        'headline-lg': ['Quicksand'],
        'body-lg': ['Inter'],
        'micro': ['Inter'],
        'display-hero': ['Quicksand'],
        'headline-md': ['Quicksand'],
        'body-sm': ['Inter'],
        'display-hero-mobile': ['Quicksand'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        'full': '9999px',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      animation: {
        'fade-in': 'fade-in 0.5s ease-out forwards',
        'slide-up': 'slide-up 0.5s ease-out forwards',
        'slide-down': 'slide-down 0.5s ease-out forwards',
        'scale-in': 'scale-in 0.3s ease-out forwards',
        'spin-once': 'spin-once 0.6s ease-in-out',
        'float': 'float 15s infinite ease-in-out',
        'float-mini': 'float-mini 3s infinite ease-in-out',
        shimmer: 'shimmer 2s linear infinite',
        gradient: 'gradient 6s ease infinite',
        wiggle: 'wiggle 0.5s ease-in-out',
        'draw-in': 'draw-in 1s ease-out forwards',
        'pop-in': 'pop-in 0.6s cubic-bezier(0.34, 1.56, 0.64, 1) forwards',
        'stagger': 'staggerFadeIn 0.4s ease-out forwards',
        'pulse-glow': 'pulseGlow 2.5s infinite',
        'slide-in-left': 'slideInLeft 0.4s ease-out forwards',
        'slide-in-right': 'slideInRight 0.4s ease-out forwards',
        'scale-bounce': 'scaleBounce 0.5s ease-out forwards',
        'gradient-text': 'gradientShift 4s ease infinite',
        'page-enter': 'pageEnter 0.3s ease-out',
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          '0%': { transform: 'translateY(-20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'spin-once': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'float': {
          '0%': { transform: 'translate(0, 0) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0, 0) scale(1)' },
        },
        'float-mini': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        gradient: {
          '0%, 100%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%': { transform: 'rotate(-3deg)' },
          '75%': { transform: 'rotate(3deg)' },
        },
        'draw-in': {
          '0%': { strokeDashoffset: '100', opacity: '0' },
          '100%': { strokeDashoffset: '0', opacity: '1' },
        },
        'pop-in': {
          '0%': { opacity: '0', transform: 'scale(0.9) translateY(20px)' },
          '100%': { opacity: '1', transform: 'scale(1) translateY(0)' },
        },
        staggerFadeIn: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        pulseGlow: {
          '0%, 100%': { boxShadow: '0 0 0 0 rgba(var(--primary-rgb), 0.3)' },
          '50%': { boxShadow: '0 0 20px 4px rgba(var(--primary-rgb), 0.15)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(-20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(20px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleBounce: {
          '0%': { transform: 'scale(0.3)', opacity: '0' },
          '50%': { transform: 'scale(1.05)' },
          '70%': { transform: 'scale(0.95)' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        gradientShift: {
          '0%': { backgroundPosition: '0% 50%' },
          '50%': { backgroundPosition: '100% 50%' },
          '100%': { backgroundPosition: '0% 50%' },
        },
        pageEnter: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
