import {
  Braces,
  Regex,
  Binary,
  Link,
  Clock,
  Shuffle,
  GitCompare,
  Type,
  ArrowLeftRight,
  Shield,
  Globe,
  Database,
  Fingerprint,
  KeyRound,
  Code2,
  Languages,
  Calculator,
  FileText,
  FileKey2,
  Palette,
  Image,
  Search,
  Wifi,
  Code,
  Zap,
  QrCode,
  FileOutput,
  Brain,
  ScanLine,
  Languages as Translate,
  Ruler,
  Calendar,
  Lock,
  Sparkles,
  Eraser,
  Video,
  FileSearch,
  PenTool,
  StickyNote,
  Crop,
  Droplets,
  AppWindow,
} from 'lucide-react';
import type { InternalTool, ExternalTool } from '../types/tool';
import { registerTool } from '../lib/tool-registry';

import JsonFormatter from './json-formatter';
import RegexTester from './regex-tester';
import Base64Tool from './base64';
import UrlEncode from './url-encode';
import Timestamp from './timestamp';
import DataGenerator from './data-generator';
import TextDiff from './text-diff';
import CharCounter from './char-counter';
import JsonYaml from './json-yaml';
import HashCalculator from './hash-calculator';
import ApiDebugger from './api-debugger';
import SqlFormatter from './sql-formatter';
import UuidGenerator from './uuid-generator';
import JwtDecoder from './jwt-decoder';
import HtmlEntities from './html-entities';
import UnicodeConverter from './unicode-converter';
import NumberBaseTool from './number-base';
import PasswordGenerator from './password-generator';
import MarkdownPreview from './markdown-preview';
import TextEncrypt from './text-encrypt';
import ColorPicker from './color-picker';
import CronGenerator from './cron-generator';
import LoremGenerator from './lorem-generator';
import HttpStatus from './http-status';
import JsonPath from './json-path';
import CssGradient from './css-gradient';
import IpLookup from './ip-lookup';
import ImageCrop from './image-crop';
import Watermark from './watermark';
import IcoGenerator from './ico-generator';
import ImageConverter from './image-converter';

const internalTools: InternalTool[] = [
  {
    type: 'internal',
    id: 'json-formatter',
    name: 'JSON 格式化',
    description: '格式化、压缩和校验 JSON 数据',
    icon: <Braces size={18} />,
    category: 'format',
    component: JsonFormatter,
    keywords: ['json', '格式化', '压缩', '校验', '美化'],
    placeholder: '粘贴 JSON 数据...',
  },
  {
    type: 'internal',
    id: 'json-path',
    name: 'JSONPath 查询',
    description: '使用 JSONPath 表达式查询 JSON 数据',
    icon: <Search size={18} />,
    category: 'format',
    component: JsonPath,
    keywords: ['jsonpath', 'json', '查询', '路径', 'path', '搜索'],
  },
  {
    type: 'internal',
    id: 'regex-tester',
    name: '正则表达式测试器',
    description: '实时测试正则表达式匹配',
    icon: <Regex size={18} />,
    category: 'format',
    component: RegexTester,
    keywords: ['正则', 'regex', '匹配', '表达式', '模式'],
  },
  {
    type: 'internal',
    id: 'sql-formatter',
    name: 'SQL 格式化',
    description: '格式化和压缩 SQL 语句',
    icon: <Database size={18} />,
    category: 'format',
    component: SqlFormatter,
    keywords: ['sql', '格式化', '压缩', '美化', '数据库'],
  },
  {
    type: 'internal',
    id: 'jwt-decoder',
    name: 'JWT 解码器',
    description: '解码和验证 JSON Web Token',
    icon: <FileKey2 size={18} />,
    category: 'format',
    component: JwtDecoder,
    keywords: ['jwt', 'token', '解码', '验证', '过期'],
  },
  {
    type: 'internal',
    id: 'cron-generator',
    name: 'Cron 表达式生成器',
    description: '可视化生成和解析 Cron 表达式',
    icon: <Clock size={18} />,
    category: 'format',
    component: CronGenerator,
    keywords: ['cron', '定时', '表达式', 'crontab', '调度'],
  },
  {
    type: 'internal',
    id: 'base64',
    name: 'Base64 编解码',
    description: '编码和解码 Base64 数据',
    icon: <Binary size={18} />,
    category: 'encode',
    component: Base64Tool,
    keywords: ['base64', '编码', '解码', '加密'],
  },
  {
    type: 'internal',
    id: 'url-encode',
    name: 'URL 编解码',
    description: 'URL 编码解码和参数解析',
    icon: <Link size={18} />,
    category: 'encode',
    component: UrlEncode,
    keywords: ['url', '编码', '解码', '参数', 'query'],
  },
  {
    type: 'internal',
    id: 'html-entities',
    name: 'HTML 实体编解码',
    description: 'HTML 实体编码和解码',
    icon: <Code2 size={18} />,
    category: 'encode',
    component: HtmlEntities,
    keywords: ['html', '实体', '编码', '解码', '转义'],
  },
  {
    type: 'internal',
    id: 'unicode-converter',
    name: 'Unicode 转换',
    description: '文本与 Unicode 编码互转',
    icon: <Languages size={18} />,
    category: 'encode',
    component: UnicodeConverter,
    keywords: ['unicode', '编码', '解码', '转义', '字符'],
  },
  {
    type: 'internal',
    id: 'hash-calculator',
    name: '哈希计算器',
    description: '计算文本和文件的哈希值',
    icon: <Shield size={18} />,
    category: 'encode',
    component: HashCalculator,
    keywords: ['哈希', 'hash', 'md5', 'sha', 'sha256', 'sha512'],
  },
  {
    type: 'internal',
    id: 'text-encrypt',
    name: '文本加密解密',
    description: 'AES-GCM / XOR / Caesar 加密与解密',
    icon: <Lock size={18} />,
    category: 'encode',
    component: TextEncrypt,
    keywords: ['加密', '解密', 'AES', 'XOR', 'Caesar', '密码', 'encrypt', 'decrypt'],
  },
  {
    type: 'internal',
    id: 'json-yaml',
    name: 'JSON ↔ YAML',
    description: 'JSON 和 YAML 双向转换',
    icon: <ArrowLeftRight size={18} />,
    category: 'convert',
    component: JsonYaml,
    keywords: ['json', 'yaml', '转换', 'yml'],
  },
  {
    type: 'internal',
    id: 'timestamp',
    name: '时间戳转换',
    description: 'Unix 时间戳与日期互转',
    icon: <Clock size={18} />,
    category: 'convert',
    component: Timestamp,
    keywords: ['时间戳', 'timestamp', '日期', 'unix', '时区'],
  },
  {
    type: 'internal',
    id: 'number-base',
    name: '进制转换',
    description: '二进制、八进制、十进制、十六进制互转',
    icon: <Calculator size={18} />,
    category: 'convert',
    component: NumberBaseTool,
    keywords: ['进制', '二进制', '八进制', '十进制', '十六进制', 'bin', 'hex'],
  },
  {
    type: 'internal',
    id: 'color-picker',
    name: '颜色工具',
    description: 'HEX/RGB/HSL 互转与配色方案',
    icon: <Palette size={18} />,
    category: 'convert',
    component: ColorPicker,
    keywords: ['颜色', 'color', 'hex', 'rgb', 'hsl', '配色', '取色'],
  },
  {
    type: 'internal',
    id: 'css-gradient',
    name: 'CSS 渐变生成器',
    description: '可视化生成 CSS 线性/径向渐变代码',
    icon: <Palette size={18} />,
    category: 'convert',
    component: CssGradient,
    keywords: ['css', '渐变', 'gradient', '线性', '径向', '背景', '配色'],
  },
  {
    type: 'internal',
    id: 'data-generator',
    name: '随机数据生成',
    description: '生成中国特化测试数据',
    icon: <Shuffle size={18} />,
    category: 'generate',
    component: DataGenerator,
    keywords: ['随机', '生成', '手机号', '身份证', '邮箱', '姓名', '测试数据'],
  },
  {
    type: 'internal',
    id: 'uuid-generator',
    name: 'UUID 生成器',
    description: '批量生成 UUID v4',
    icon: <Fingerprint size={18} />,
    category: 'generate',
    component: UuidGenerator,
    keywords: ['uuid', '生成', '唯一标识', 'v4', '批量'],
  },
  {
    type: 'internal',
    id: 'password-generator',
    name: '密码生成器',
    description: '生成安全的随机密码',
    icon: <KeyRound size={18} />,
    category: 'generate',
    component: PasswordGenerator,
    keywords: ['密码', '生成', 'password', '随机', '安全'],
  },
  {
    type: 'internal',
    id: 'lorem-generator',
    name: '占位文本生成',
    description: '生成中文/英文占位文本和测试数据',
    icon: <StickyNote size={18} />,
    category: 'generate',
    component: LoremGenerator,
    keywords: ['占位', 'lorem', '中文段落', '英文段落', '标题', '地址', '公司'],
  },
  {
    type: 'internal',
    id: 'text-diff',
    name: '文本 Diff 对比',
    description: '比较两段文本的差异',
    icon: <GitCompare size={18} />,
    category: 'text',
    component: TextDiff,
    keywords: ['diff', '对比', '差异', '比较'],
  },
  {
    type: 'internal',
    id: 'char-counter',
    name: '字符统计',
    description: '统计文本字符数、行数、字节数',
    icon: <Type size={18} />,
    category: 'text',
    component: CharCounter,
    keywords: ['字符', '统计', '字数', '行数', '字节'],
  },
  {
    type: 'internal',
    id: 'markdown-preview',
    name: 'Markdown 预览',
    description: '实时 Markdown 渲染预览',
    icon: <FileText size={18} />,
    category: 'text',
    component: MarkdownPreview,
    keywords: ['markdown', '预览', '渲染', 'md', '实时'],
  },
  {
    type: 'internal',
    id: 'api-debugger',
    name: 'API 调试',
    description: '轻量级 HTTP 请求调试工具',
    icon: <Globe size={18} />,
    category: 'network',
    component: ApiDebugger,
    keywords: ['api', 'http', '请求', '调试', 'postman', '接口'],
  },
  {
    type: 'internal',
    id: 'http-status',
    name: 'HTTP 状态码查询',
    description: '查询 HTTP 状态码含义及常见测试场景',
    icon: <Wifi size={18} />,
    category: 'network',
    component: HttpStatus,
    keywords: ['http', '状态码', 'status', 'code', '404', '500', '响应码'],
  },
  {
    type: 'internal',
    id: 'ip-lookup',
    name: 'IP 地址查询',
    description: '查询 IP 地址的地理位置与网络信息',
    icon: <Wifi size={18} />,
    category: 'network',
    component: IpLookup,
    keywords: ['ip', '地址', '查询', '地理位置', 'isp', '网络', 'ipv4'],
  },
  {
    type: 'internal',
    id: 'image-crop',
    name: '图片裁剪',
    description: '裁剪、压缩、精灵图检测，支持 SVG/PNG/JPG/WebP',
    icon: <Crop size={18} />,
    category: 'convert',
    component: ImageCrop,
    keywords: ['图片', '裁剪', 'crop', '压缩', '精灵图', 'sprite', 'SVG', 'WebP', 'EXIF'],
  },
  {
    type: 'internal',
    id: 'watermark',
    name: '图片水印',
    description: '为图片添加文字或图片水印，支持平铺和9宫格定位',
    icon: <Droplets size={18} />,
    category: 'convert',
    component: Watermark,
    keywords: ['水印', 'watermark', '文字水印', '图片水印', '平铺', '版权'],
  },
  {
    type: 'internal',
    id: 'ico-generator',
    name: 'ICO 图标生成',
    description: '上传图片生成多尺寸 ICO / PNG 图标文件',
    icon: <AppWindow size={18} />,
    category: 'convert',
    component: IcoGenerator,
    keywords: ['ico', '图标', 'icon', 'favicon', '生成', '多尺寸', 'PNG'],
  },
  {
    type: 'internal',
    id: 'image-converter',
    name: '图片格式转换',
    description: '批量转换图片格式，支持 PNG/JPEG/WebP/BMP/ICO',
    icon: <Image size={18} />,
    category: 'convert',
    component: ImageConverter,
    keywords: ['图片', '格式', '转换', 'convert', 'png', 'jpg', 'webp', 'bmp', 'ico', '批量'],
  },
];

const externalTools: ExternalTool[] = [
  {
    type: 'external',
    id: 'image-compress',
    name: '图片压缩',
    description: '在线压缩 PNG/JPG 图片',
    icon: <Image size={18} />,
    category: 'external',
    externalUrl: 'https://www.yalijuda.com',
    alternatives: [
      { name: 'TinyPNG 中文', url: 'https://tinypng.com/cn', description: 'PNG/JPG 智能压缩' },
      { name: '67tool 图片压缩', url: 'https://www.67tool.com/image-compress', description: '批量图片压缩' },
    ],
    keywords: ['图片', '压缩', 'image', 'png', 'jpg', 'compress'],
  },
  {
    type: 'external',
    id: 'watermark-remover',
    name: '去水印',
    description: 'AI 智能去除图片/视频水印',
    icon: <Eraser size={18} />,
    category: 'external',
    externalUrl: 'https://clean.lazyso.com',
    alternatives: [
      { name: '灵猫去水印', url: 'https://clearcat.lingxiangtools.top', description: '多平台去水印' },
      { name: '67tool 去水印', url: 'https://www.67tool.com/watermark', description: '在线去水印工具' },
    ],
    keywords: ['水印', '去除', '去水印', 'watermark', 'AI'],
  },
  {
    type: 'external',
    id: 'video-compress',
    name: '视频压缩',
    description: '在线压缩视频文件大小',
    icon: <Video size={18} />,
    category: 'external',
    externalUrl: 'https://videocompressors.com/zh',
    alternatives: [
      { name: '67tool 视频压缩', url: 'https://www.67tool.com/video-compress', description: '在线视频压缩' },
      { name: 'YouCompress', url: 'https://www.youcompress.com/zh', description: '免费视频压缩' },
    ],
    keywords: ['视频', '压缩', 'video', 'compress', 'mp4'],
  },
  {
    type: 'external',
    id: 'ai-tools',
    name: 'AI 工具集',
    description: 'AI 写作/绘画/对话/编程工具',
    icon: <Sparkles size={18} />,
    category: 'external',
    externalUrl: 'https://ai-bot.cn',
    alternatives: [
      { name: 'AI 导航', url: 'https://www.ainav.cn', description: 'AI 工具导航站' },
      { name: 'ChatGPT', url: 'https://chat.openai.com', description: 'OpenAI 对话' },
    ],
    keywords: ['ai', '人工智能', '写作', '绘画', '对话', 'chatgpt'],
  },
  {
    type: 'external',
    id: 'doc-parser',
    name: '文档解析',
    description: 'PDF/Word/PPT 智能解析提取',
    icon: <FileSearch size={18} />,
    category: 'external',
    externalUrl: 'https://mineru.net',
    alternatives: [
      { name: '67tool PDF转Word', url: 'https://www.67tool.com/pdf-to-word', description: 'PDF 转 Word' },
      { name: 'iLovePDF', url: 'https://www.ilovepdf.com/zh-cn', description: 'PDF 全功能工具' },
    ],
    keywords: ['文档', '解析', 'PDF', 'Word', '提取', 'MinerU'],
  },
  {
    type: 'external',
    id: 'online-whiteboard',
    name: '在线画板',
    description: '在线白板和绘图工具',
    icon: <PenTool size={18} />,
    category: 'external',
    externalUrl: 'https://excalidraw.com',
    alternatives: [
      { name: 'BoardOS', url: 'https://boardos.com', description: '国产在线白板' },
      { name: 'Draw.io', url: 'https://app.diagrams.net', description: '流程图绘制' },
    ],
    keywords: ['画板', '白板', '绘图', '流程图', 'excalidraw'],
  },
  {
    type: 'external',
    id: 'regex-visual',
    name: '正则可视化',
    description: '可视化正则表达式结构',
    icon: <Regex size={18} />,
    category: 'external',
    externalUrl: 'https://tool.lu/regex',
    alternatives: [
      { name: 'Regulex', url: 'https://jex.im/regulex', description: '正则表达式可视化' },
      { name: '67tool 正则', url: 'https://www.67tool.com/regex', description: '正则在线测试' },
    ],
    keywords: ['正则', 'regex', '可视化', '调试'],
  },
  {
    type: 'external',
    id: 'code-sandbox',
    name: '在线代码运行',
    description: '在线编辑和运行代码',
    icon: <Code size={18} />,
    category: 'external',
    externalUrl: 'https://codepen.io',
    alternatives: [
      { name: 'JSFiddle', url: 'https://jsfiddle.net', description: '在线 JS/HTML/CSS 编辑器' },
      { name: 'StackBlitz', url: 'https://stackblitz.com', description: '在线全栈开发环境' },
    ],
    keywords: ['代码', '在线', '运行', '沙箱', 'codepen', 'jsfiddle'],
  },
  {
    type: 'external',
    id: 'network-tools',
    name: '网络检测工具',
    description: 'IP/DNS/端口检测',
    icon: <Wifi size={18} />,
    category: 'external',
    externalUrl: 'https://www.ip138.com',
    alternatives: [
      { name: '站长工具 IP', url: 'https://tool.chinaz.com/ip', description: 'IP 地址查询' },
      { name: '站长工具 端口', url: 'https://tool.chinaz.com/port', description: '端口扫描检测' },
    ],
    keywords: ['ip', 'dns', '端口', '网络', '检测'],
  },
  {
    type: 'external',
    id: 'api-mock',
    name: 'API Mock 服务',
    description: '创建模拟 API 接口',
    icon: <Zap size={18} />,
    category: 'external',
    externalUrl: 'https://designer.mocky.io',
    alternatives: [
      { name: 'JSONPlaceholder', url: 'https://jsonplaceholder.typicode.com', description: '免费在线 Mock API' },
      { name: 'FastMock', url: 'https://fastmock.site', description: '国内 Mock 服务' },
    ],
    keywords: ['mock', 'api', '模拟', '接口', '测试'],
  },
  {
    type: 'external',
    id: 'performance-test',
    name: '网站性能测试',
    description: '页面加载性能分析',
    icon: <Search size={18} />,
    category: 'external',
    externalUrl: 'https://www.webpagetest.org',
    alternatives: [
      { name: '17CE', url: 'https://www.17ce.com', description: '国内网站测速' },
      { name: '站长工具 测速', url: 'https://tool.chinaz.com/speed', description: '网站速度测试' },
    ],
    keywords: ['性能', '速度', '测试', 'pagespeed', 'lighthouse'],
  },
  {
    type: 'external',
    id: 'pdf-tool',
    name: 'PDF 工具',
    description: 'PDF 合并/拆分/转换/压缩',
    icon: <FileOutput size={18} />,
    category: 'office',
    externalUrl: 'https://www.67tool.com/pdf',
    alternatives: [
      { name: 'Smallpdf 中文', url: 'https://smallpdf.com/cn', description: 'PDF 在线处理' },
      { name: 'iLovePDF 中文', url: 'https://www.ilovepdf.com/zh-cn', description: 'PDF 全功能工具' },
    ],
    keywords: ['pdf', '合并', '拆分', '转换', '压缩'],
  },
  {
    type: 'external',
    id: 'qrcode',
    name: '二维码生成器',
    description: '在线生成和解析二维码',
    icon: <QrCode size={18} />,
    category: 'office',
    externalUrl: 'https://cli.im',
    alternatives: [
      { name: '67tool 二维码', url: 'https://www.67tool.com/qrcode', description: '二维码生成解析' },
      { name: '草料二维码', url: 'https://www.liantu.com', description: '二维码生成器' },
    ],
    keywords: ['二维码', 'qrcode', '生成', '扫码'],
  },
  {
    type: 'external',
    id: 'short-url',
    name: '短链接生成器',
    description: '长链接转短链接',
    icon: <Link size={18} />,
    category: 'office',
    externalUrl: 'https://tool.chinaz.com/tools/dwz.aspx',
    alternatives: [
      { name: '67tool 短链接', url: 'https://www.67tool.com/short-url', description: '短链接生成' },
    ],
    keywords: ['短链接', 'short url', '缩短'],
  },
  {
    type: 'external',
    id: 'mind-map',
    name: '思维导图',
    description: '在线思维导图和流程图',
    icon: <Brain size={18} />,
    category: 'office',
    externalUrl: 'https://www.processon.com',
    alternatives: [
      { name: '知犀思维导图', url: 'https://www.zhixi.com', description: '免费思维导图' },
      { name: '幕布', url: 'https://mubu.com', description: '大纲笔记转思维导图' },
    ],
    keywords: ['思维导图', '流程图', 'processon', '脑图'],
  },
  {
    type: 'external',
    id: 'ocr-tool',
    name: 'OCR 文字识别',
    description: '图片文字识别提取',
    icon: <ScanLine size={18} />,
    category: 'office',
    externalUrl: 'https://www.67tool.com/ocr',
    alternatives: [
      { name: '白描 OCR', url: 'https://baimiao.app', description: '高精度文字识别' },
      { name: 'PearOCR', url: 'https://pearocr.com', description: '本地 OCR 识别' },
    ],
    keywords: ['ocr', '文字识别', '图片转文字'],
  },
  {
    type: 'external',
    id: 'translate-tool',
    name: '在线翻译',
    description: '多语言在线翻译',
    icon: <Translate size={18} />,
    category: 'office',
    externalUrl: 'https://fanyi.baidu.com',
    alternatives: [
      { name: 'DeepL', url: 'https://www.deepl.com/zh/translator', description: 'AI 高质量翻译' },
      { name: '有道翻译', url: 'https://fanyi.youdao.com', description: '网易有道翻译' },
    ],
    keywords: ['翻译', 'translate', '百度翻译', '中英'],
  },
  {
    type: 'external',
    id: 'unit-converter',
    name: '单位换算',
    description: '长度/重量/温度/面积等单位换算',
    icon: <Ruler size={18} />,
    category: 'office',
    externalUrl: 'https://www.67tool.com/unit-converter',
    alternatives: [
      { name: 'Tool.lu 单位换算', url: 'https://tool.lu/unit', description: '多单位换算' },
    ],
    keywords: ['单位', '换算', '长度', '重量', '温度'],
  },
  {
    type: 'external',
    id: 'calendar-tool',
    name: '日历/老黄历',
    description: '万年历、节假日、老黄历查询',
    icon: <Calendar size={18} />,
    category: 'office',
    externalUrl: 'https://wannianrili.bmcx.com',
    alternatives: [
      { name: '67tool 日历', url: 'https://www.67tool.com/calendar', description: '万年历查询' },
    ],
    keywords: ['日历', '老黄历', '万年历', '节假日'],
  },
  {
    type: 'external',
    id: 'tool-lu',
    name: 'Tool.lu 工具箱',
    description: '国内知名综合在线工具箱',
    icon: <Globe size={18} />,
    category: 'external',
    externalUrl: 'https://tool.lu',
    alternatives: [
      { name: '67tool', url: 'https://www.67tool.com', description: '综合在线工具箱' },
      { name: '站长工具', url: 'https://tool.chinaz.com', description: '站长综合工具' },
    ],
    keywords: ['工具箱', '在线工具', '综合', 'tool.lu'],
  },
];

export function registerAllTools() {
  for (const tool of internalTools) registerTool(tool);
  for (const tool of externalTools) registerTool(tool);
}

export { internalTools, externalTools };
