/** @type {import('tailwindcss').Config} */

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
    },
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        'primary-hover': 'var(--color-primary-hover)',
        'primary-light': 'var(--color-primary-light)',
        secondary: 'var(--color-secondary)',
        'secondary-light': 'var(--color-secondary-light)',
        cta: 'var(--color-cta)',
        'cta-light': 'var(--color-cta-light)',
        'bg-primary': 'var(--color-bg-primary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        'bg-elevated': 'var(--color-bg-elevated)',
        surface: 'var(--color-surface)',
        'surface-hover': 'var(--color-surface-hover)',
        border: 'var(--color-border)',
        'border-hover': 'var(--color-border-hover)',
        'border-light': 'var(--color-border)',
        'border-focus': 'var(--color-border-focus)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-muted': 'var(--color-text-muted)',
        'text-inverse': 'var(--color-text-inverse)',
        error: 'var(--color-error)',
        'error-light': 'var(--color-error-light)',
        success: 'var(--color-success)',
        'success-light': 'var(--color-success-light)',
        warning: 'var(--color-warning)',
        'warning-light': 'var(--color-warning-light)',
        info: 'var(--color-info)',
        'info-light': 'var(--color-info-light)',
        'clay-pink': { light: 'var(--clay-pink-light)', DEFAULT: 'var(--clay-pink-main)', medium: 'var(--clay-pink-medium)', dark: 'var(--clay-pink-dark)', deep: 'var(--clay-pink-deep)' },
        'clay-blue': { light: 'var(--clay-blue-light)', DEFAULT: 'var(--clay-blue-main)', medium: 'var(--clay-blue-medium)', dark: 'var(--clay-blue-dark)' },
        'clay-purple': { light: 'var(--clay-purple-light)', DEFAULT: 'var(--clay-purple-main)', medium: 'var(--clay-purple-medium)', dark: 'var(--clay-purple-dark)' },
        'clay-green': { light: 'var(--clay-green-light)', DEFAULT: 'var(--clay-green-main)', medium: 'var(--clay-green-medium)', dark: 'var(--clay-green-dark)' },
        'clay-yellow': { light: 'var(--clay-yellow-light)', DEFAULT: 'var(--clay-yellow-main)', medium: 'var(--clay-yellow-medium)', dark: 'var(--clay-yellow-dark)' },
        'clay-white': 'var(--clay-white)',
        'clay-gray': { light: 'var(--clay-gray-light)', medium: 'var(--clay-gray-medium)' },
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
        sans: ['Inter', 'Nunito', 'Quicksand', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        '2xl': '1rem',
        '3xl': '1.5rem',
        '4xl': '2rem',
        'clay-sm': '16px',
        'clay': '24px',
        'clay-lg': '32px',
        'clay-xl': '48px',
        'clay-full': '50px',
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
};
