import { lazy } from 'react';
import {
  Braces,
  Search,
  Regex,
  Database,
  FileKey2,
  Clock,
  Binary,
  Link,
  Code2,
  Languages,
  Shield,
  Lock,
  ArrowLeftRight,
  Calculator,
  Palette,
  Shuffle,
  Fingerprint,
  KeyRound,
  StickyNote,
  GitCompare,
  Type,
  FileText,
  Globe,
  Wifi,
  Crop,
  Droplets,
  AppWindow,
  Sparkles,
  Eraser,
  Video,
  FileSearch,
  PenTool,
  Code,
  Zap,
  Ruler,
  Barcode,
  FileOutput,
  Brain,
  ScanLine,
} from 'lucide-react';
import { registerTool } from '../lib/tool-registry';
const JsonFormatter = lazy(() => import('./json-formatter'));
const RegexTester = lazy(() => import('./regex-tester'));
const SqlFormatter = lazy(() => import('./sql-formatter'));
const JwtDecoder = lazy(() => import('./jwt-decoder'));
const CronGenerator = lazy(() => import('./cron-generator'));
const Base64 = lazy(() => import('./base64'));
const UrlEncode = lazy(() => import('./url-encode'));
const HtmlEntities = lazy(() => import('./html-entities'));
const UnicodeConverter = lazy(() => import('./unicode-converter'));
const HashCalculator = lazy(() => import('./hash-calculator'));
const TextEncrypt = lazy(() => import('./text-encrypt'));
const JsonYaml = lazy(() => import('./json-yaml'));
const Timestamp = lazy(() => import('./timestamp'));
const NumberBase = lazy(() => import('./number-base'));
const ColorPicker = lazy(() => import('./color-picker'));
const CssGradient = lazy(() => import('./css-gradient'));
const ImageCrop = lazy(() => import('./image-crop'));
const Watermark = lazy(() => import('./watermark'));
const IcoGenerator = lazy(() => import('./ico-generator'));
const DataGenerator = lazy(() => import('./data-generator'));
const UuidGenerator = lazy(() => import('./uuid-generator'));
const PasswordGenerator = lazy(() => import('./password-generator'));
const LoremGenerator = lazy(() => import('./lorem-generator'));
const TextDiff = lazy(() => import('./text-diff'));
const CharCounter = lazy(() => import('./char-counter'));
const MarkdownPreview = lazy(() => import('./markdown-preview'));
const ApiDebugger = lazy(() => import('./api-debugger'));
const HttpStatus = lazy(() => import('./http-status'));
const IpLookup = lazy(() => import('./ip-lookup'));
const CodeGenerator = lazy(() => import('./code-generator'));
const UnitConverter = lazy(() => import('./unit-converter'));

const internalTools = [
  {
    type: 'internal' as const,
    id: 'json-formatter',
    name: 'JSON 格式化',
    description: '格式化、压缩、校验和查询 JSON 数据',
    icon: <Braces size={18} />,
    category: 'format' as const,
    component: JsonFormatter,
    keywords: ['json', '格式化', '压缩', '校验', '美化', 'jsonpath', '查询', '路径', 'path', '搜索'],
    placeholder: '粘贴 JSON 数据...',
  },
  {
    type: 'internal' as const,
    id: 'regex-tester',
    name: '正则表达式测试',
    description: '在线测试和调试正则表达式',
    icon: <Regex size={18} />,
    category: 'format' as const,
    component: RegexTester,
    keywords: ['正则', 'regex', '匹配', '表达式', '模式'],
  },
  {
    type: 'internal' as const,
    id: 'sql-formatter',
    name: 'SQL 格式化',
    description: '格式化和美化 SQL 语句',
    icon: <Database size={18} />,
    category: 'format' as const,
    component: SqlFormatter,
    keywords: ['sql', '格式化', '压缩', '美化', '数据库'],
  },
  {
    type: 'internal' as const,
    id: 'jwt-decoder',
    name: 'JWT 解码器',
    description: '解码和验证 JWT Token',
    icon: <FileKey2 size={18} />,
    category: 'format' as const,
    component: JwtDecoder,
    keywords: ['jwt', 'token', '解码', '验证', '过期'],
  },
  {
    type: 'internal' as const,
    id: 'cron-generator',
    name: 'Cron 表达式生成器',
    description: '可视化和生成 Cron 定时表达式',
    icon: <Clock size={18} />,
    category: 'format' as const,
    component: CronGenerator,
    keywords: ['cron', '定时', '表达式', 'crontab', '调度'],
  },
  {
    type: 'internal' as const,
    id: 'base64',
    name: 'Base64 编解码',
    description: 'Base64 编码和解码工具',
    icon: <Binary size={18} />,
    category: 'encode' as const,
    component: Base64,
    keywords: ['base64', '编码', '解码', '加密'],
  },
  {
    type: 'internal' as const,
    id: 'url-encode',
    name: 'URL 编解码',
    description: 'URL 编码和解码工具',
    icon: <Link size={18} />,
    category: 'encode' as const,
    component: UrlEncode,
    keywords: ['url', '编码', '解码', '参数', 'query'],
  },
  {
    type: 'internal' as const,
    id: 'html-entities',
    name: 'HTML 实体编解码',
    description: 'HTML 实体编码和解码工具',
    icon: <Code2 size={18} />,
    category: 'encode' as const,
    component: HtmlEntities,
    keywords: ['html', '实体', '编码', '解码', '转义'],
  },
  {
    type: 'internal' as const,
    id: 'unicode-converter',
    name: 'Unicode 转换器',
    description: 'Unicode 编码和解码转换',
    icon: <Languages size={18} />,
    category: 'encode' as const,
    component: UnicodeConverter,
    keywords: ['unicode', '编码', '解码', '转义', '字符'],
  },
  {
    type: 'internal' as const,
    id: 'hash-calculator',
    name: '哈希计算器',
    description: '计算文本的 MD5/SHA 哈希值',
    icon: <Shield size={18} />,
    category: 'encode' as const,
    component: HashCalculator,
    keywords: ['哈希', 'hash', 'md5', 'sha', 'sha256', 'sha512'],
  },
  {
    type: 'internal' as const,
    id: 'text-encrypt',
    name: '文本加密解密',
    description: 'AES/XOR/Caesar 等加密解密',
    icon: <Lock size={18} />,
    category: 'encode' as const,
    component: TextEncrypt,
    keywords: ['加密', '解密', 'AES', 'XOR', 'Caesar', '密码', 'encrypt', 'decrypt'],
  },
  {
    type: 'internal' as const,
    id: 'json-yaml',
    name: 'JSON ↔ YAML 转换',
    description: 'JSON 和 YAML 格式互转',
    icon: <ArrowLeftRight size={18} />,
    category: 'convert' as const,
    component: JsonYaml,
    keywords: ['json', 'yaml', '转换', 'yml'],
  },
  {
    type: 'internal' as const,
    id: 'timestamp',
    name: '时间戳转换',
    description: '时间戳与日期格式互转',
    icon: <Clock size={18} />,
    category: 'convert' as const,
    component: Timestamp,
    keywords: ['时间戳', 'timestamp', '日期', 'unix', '时区'],
  },
  {
    type: 'internal' as const,
    id: 'number-base',
    name: '进制转换',
    description: '二进制/八进制/十进制/十六进制互转',
    icon: <Calculator size={18} />,
    category: 'convert' as const,
    component: NumberBase,
    keywords: ['进制', '二进制', '八进制', '十进制', '十六进制', 'bin', 'hex'],
  },
  {
    type: 'internal' as const,
    id: 'color-picker',
    name: '颜色选择器',
    description: '颜色选取和格式转换 HEX/RGB/HSL',
    icon: <Palette size={18} />,
    category: 'convert' as const,
    component: ColorPicker,
    keywords: ['颜色', 'color', 'hex', 'rgb', 'hsl', '配色', '取色'],
  },
  {
    type: 'internal' as const,
    id: 'css-gradient',
    name: 'CSS 渐变生成器',
    description: '可视化生成 CSS 渐变背景',
    icon: <Palette size={18} />,
    category: 'convert' as const,
    component: CssGradient,
    keywords: ['css', '渐变', 'gradient', '线性', '径向', '背景', '配色'],
  },
  {
    type: 'internal' as const,
    id: 'image-crop',
    name: '图片处理',
    description: '图片裁剪、压缩、格式转换、精灵图检测，支持 SVG/PNG/JPG/WebP 等格式',
    icon: <Crop size={18} />,
    category: 'convert' as const,
    component: ImageCrop,
    keywords: ['图片', '裁剪', 'crop', '压缩', '精灵图', 'sprite', 'SVG', 'WebP', 'EXIF', '格式', '转换', 'convert', 'png', 'jpg', 'webp', 'bmp', 'ico', '批量'],
  },
  {
    type: 'internal' as const,
    id: 'watermark',
    name: '水印添加',
    description: '为图片添加文字或图片水印',
    icon: <Droplets size={18} />,
    category: 'convert' as const,
    component: Watermark,
    keywords: ['水印', 'watermark', '文字水印', '图片水印', '平铺', '版权'],
  },
  {
    type: 'internal' as const,
    id: 'ico-generator',
    name: 'ICO 图标生成器',
    description: '从图片生成多尺寸 ICO/Favicon 图标',
    icon: <AppWindow size={18} />,
    category: 'convert' as const,
    component: IcoGenerator,
    keywords: ['ico', '图标', 'icon', 'favicon', '生成', '多尺寸', 'PNG'],
  },
  {
    type: 'internal' as const,
    id: 'data-generator',
    name: '测试数据生成器',
    description: '生成随机手机号/身份证/邮箱等测试数据',
    icon: <Shuffle size={18} />,
    category: 'generate' as const,
    component: DataGenerator,
    keywords: ['随机', '生成', '手机号', '身份证', '邮箱', '姓名', '测试数据'],
  },
  {
    type: 'internal' as const,
    id: 'uuid-generator',
    name: 'UUID 生成器',
    description: '批量生成 UUID v4 唯一标识符',
    icon: <Fingerprint size={18} />,
    category: 'generate' as const,
    component: UuidGenerator,
    keywords: ['uuid', '生成', '唯一标识', 'v4', '批量'],
  },
  {
    type: 'internal' as const,
    id: 'password-generator',
    name: '密码生成器',
    description: '生成安全的随机密码',
    icon: <KeyRound size={18} />,
    category: 'generate' as const,
    component: PasswordGenerator,
    keywords: ['密码', '生成', 'password', '随机', '安全'],
  },
  {
    type: 'internal' as const,
    id: 'lorem-generator',
    name: '占位文本生成器',
    description: '生成中英文占位文本和段落',
    icon: <StickyNote size={18} />,
    category: 'generate' as const,
    component: LoremGenerator,
    keywords: ['占位', 'lorem', '中文段落', '英文段落', '标题', '地址', '公司'],
  },
  {
    type: 'internal' as const,
    id: 'text-diff',
    name: '文本对比',
    description: '对比两段文本的差异',
    icon: <GitCompare size={18} />,
    category: 'text' as const,
    component: TextDiff,
    keywords: ['diff', '对比', '差异', '比较'],
  },
  {
    type: 'internal' as const,
    id: 'char-counter',
    name: '字符统计',
    description: '统计文本的字符数、行数和字节数',
    icon: <Type size={18} />,
    category: 'text' as const,
    component: CharCounter,
    keywords: ['字符', '统计', '字数', '行数', '字节'],
  },
  {
    type: 'internal' as const,
    id: 'markdown-preview',
    name: 'Markdown 预览',
    description: '实时渲染 Markdown 文档',
    icon: <FileText size={18} />,
    category: 'text' as const,
    component: MarkdownPreview,
    keywords: ['markdown', '预览', '渲染', 'md', '实时'],
  },
  {
    type: 'internal' as const,
    id: 'api-debugger',
    name: 'API 调试器',
    description: '在线调试 HTTP API 接口',
    icon: <Globe size={18} />,
    category: 'network' as const,
    component: ApiDebugger,
    keywords: ['api', 'http', '请求', '调试', 'postman', '接口'],
  },
  {
    type: 'internal' as const,
    id: 'http-status',
    name: 'HTTP 状态码查询',
    description: '查询 HTTP 响应状态码含义',
    icon: <Wifi size={18} />,
    category: 'network' as const,
    component: HttpStatus,
    keywords: ['http', '状态码', 'status', 'code', '404', '500', '响应码'],
  },
  {
    type: 'internal' as const,
    id: 'ip-lookup',
    name: 'IP 地址查询',
    description: '查询 IP 地址的地理位置和 ISP 信息',
    icon: <Wifi size={18} />,
    category: 'network' as const,
    component: IpLookup,
    keywords: ['ip', '地址', '查询', '地理位置', 'isp', '网络', 'ipv4'],
  },
  {
    type: 'internal' as const,
    id: 'code-generator',
    name: '码生成器',
    description: '生成二维码、条形码、WiFi码、vCard码等多种码',
    icon: <Barcode size={18} />,
    category: 'generate' as const,
    component: CodeGenerator,
    keywords: ['二维码', 'qrcode', '条形码', 'barcode', '生成', 'WiFi', 'vCard', 'EAN', 'CODE128'],
  },
  {
    type: 'internal' as const,
    id: 'unit-converter',
    name: '单位换算',
    description: '长度/重量/温度/面积/体积/速度/数据/时间/压力等单位换算',
    icon: <Ruler size={18} />,
    category: 'convert' as const,
    component: UnitConverter,
    keywords: ['单位', '换算', '长度', '重量', '温度', '面积', '体积', '速度', '数据', '时间', '压力'],
  },
];

const externalTools = [
  {
    type: 'external' as const,
    id: 'pdf-tool',
    name: 'PDF 工具',
    description: 'PDF 合并/拆分/转换/压缩',
    icon: <FileOutput size={18} />,
    category: 'office' as const,
    externalUrl: 'https://www.ilovepdf.com/zh-cn',
    alternatives: [
      { name: 'Smallpdf 中文', url: 'https://smallpdf.com/cn', description: 'PDF 在线处理' },
      { name: '67tool PDF', url: 'https://www.67tool.com/pdf', description: 'PDF 工具' },
    ],
    keywords: ['pdf', '合并', '拆分', '转换', '压缩'],
  },
  {
    type: 'external' as const,
    id: 'short-url',
    name: '短链接生成',
    description: '将长链接缩短为短链接',
    icon: <Link size={18} />,
    category: 'office' as const,
    externalUrl: 'https://tool.chinaz.com/tools/dwz.aspx',
    alternatives: [
      { name: '67tool 短链接', url: 'https://www.67tool.com/short-url', description: '短链接生成' },
    ],
    keywords: ['短链接', 'short url', '缩短'],
  },
  {
    type: 'external' as const,
    id: 'mind-map',
    name: '思维导图',
    description: '在线创建思维导图和流程图',
    icon: <Brain size={18} />,
    category: 'office' as const,
    externalUrl: 'https://www.processon.com',
    alternatives: [
      { name: '知犀思维导图', url: 'https://www.zhixi.com', description: '免费思维导图' },
      { name: '幕布', url: 'https://mubu.com', description: '大纲笔记' },
    ],
    keywords: ['思维导图', '流程图', 'processon', '脑图'],
  },
  {
    type: 'external' as const,
    id: 'ocr-tool',
    name: 'OCR 文字识别',
    description: '图片转文字 OCR 识别工具',
    icon: <ScanLine size={18} />,
    category: 'office' as const,
    externalUrl: 'https://pearocr.com',
    alternatives: [
      { name: '白描 OCR', url: 'https://baimiao.app', description: 'OCR 文字识别' },
      { name: '67tool OCR', url: 'https://www.67tool.com/ocr', description: '在线 OCR' },
    ],
    keywords: ['ocr', '文字识别', '图片转文字'],
  },
  {
    type: 'external' as const,
    id: 'translate-tool',
    name: '翻译工具',
    description: '多语言在线翻译',
    icon: <Languages size={18} />,
    category: 'office' as const,
    externalUrl: 'https://fanyi.baidu.com',
    alternatives: [
      { name: '有道翻译', url: 'https://fanyi.youdao.com', description: '多语言翻译' },
      { name: 'DeepL', url: 'https://www.deepl.com/zh/translator', description: 'AI 翻译' },
    ],
    keywords: ['翻译', 'translate', '百度翻译', '中英'],
  },
  {
    type: 'external' as const,
    id: 'watermark-remover',
    name: '去水印',
    description: 'AI 去除图片水印',
    icon: <Eraser size={18} />,
    category: 'external' as const,
    externalUrl: 'https://clean.lazyso.com',
    alternatives: [
      { name: '灵猫去水印', url: 'https://lingcat.com', description: '去水印工具' },
      { name: '67tool 去水印', url: 'https://www.67tool.com/watermark-remover', description: '去水印工具' },
    ],
    keywords: ['水印', '去除', '去水印', 'watermark', 'AI'],
  },
  {
    type: 'external' as const,
    id: 'video-compress',
    name: '视频压缩',
    description: '在线压缩视频文件大小',
    icon: <Video size={18} />,
    category: 'external' as const,
    externalUrl: 'https://www.67tool.com/video-compress',
    alternatives: [
      { name: 'YouCompress', url: 'https://www.youcompress.com', description: '视频压缩' },
      { name: '视频压缩器', url: 'https://videocompressors.com/zh', description: '视频压缩' },
    ],
    keywords: ['视频', '压缩', 'video', 'compress', 'mp4'],
  },
  {
    type: 'external' as const,
    id: 'ai-tools',
    name: 'AI 工具导航',
    description: 'AI 工具合集和导航',
    icon: <Sparkles size={18} />,
    category: 'external' as const,
    externalUrl: 'https://ai-bot.cn',
    alternatives: [
      { name: 'AI 导航', url: 'https://ai-bot.cn', description: 'AI 工具导航' },
      { name: 'Z.AI', url: 'https://chat.z.ai', description: 'AI 对话' },
    ],
    keywords: ['ai', '人工智能', '写作', '绘画', '对话', 'chatgpt'],
  },
  {
    type: 'external' as const,
    id: 'doc-parser',
    name: '文档解析',
    description: 'PDF/Word 文档解析和提取',
    icon: <FileSearch size={18} />,
    category: 'external' as const,
    externalUrl: 'https://mineru.net',
    alternatives: [
      { name: 'iLovePDF', url: 'https://www.ilovepdf.com/zh-cn', description: 'PDF 工具' },
      { name: '67tool PDF转Word', url: 'https://www.67tool.com/pdf-to-word', description: 'PDF 转 Word' },
    ],
    keywords: ['文档', '解析', 'PDF', 'Word', '提取', 'MinerU'],
  },
  {
    type: 'external' as const,
    id: 'online-whiteboard',
    name: '在线白板',
    description: '在线绘图和白板工具',
    icon: <PenTool size={18} />,
    category: 'external' as const,
    externalUrl: 'https://boardos.com',
    alternatives: [
      { name: 'Draw.io', url: 'https://app.diagrams.net', description: '流程图工具' },
      { name: 'Excalidraw', url: 'https://excalidraw.com', description: '手绘白板' },
    ],
    keywords: ['画板', '白板', '绘图', '流程图', 'excalidraw'],
  },
  {
    type: 'external' as const,
    id: 'regex-visual',
    name: '正则可视化',
    description: '正则表达式可视化调试工具',
    icon: <Regex size={18} />,
    category: 'external' as const,
    externalUrl: 'https://tool.lu/regex',
    alternatives: [
      { name: 'Regulex', url: 'https://jex.im/regulex', description: '正则可视化' },
      { name: '67tool 正则', url: 'https://www.67tool.com/regex', description: '正则工具' },
    ],
    keywords: ['正则', 'regex', '可视化', '调试'],
  },
  {
    type: 'external' as const,
    id: 'code-sandbox',
    name: '在线代码运行',
    description: '在线代码编辑和运行沙箱',
    icon: <Code size={18} />,
    category: 'external' as const,
    externalUrl: 'https://codejiejie.com',
    alternatives: [
      { name: 'CodePen', url: 'https://codepen.io', description: '前端代码编辑' },
      { name: 'JSFiddle', url: 'https://jsfiddle.net', description: '在线代码编辑' },
    ],
    keywords: ['代码', '在线', '运行', '沙箱', 'codepen', 'jsfiddle'],
  },
  {
    type: 'external' as const,
    id: 'network-tools',
    name: '网络工具',
    description: 'IP/DNS/端口等网络检测工具',
    icon: <Wifi size={18} />,
    category: 'external' as const,
    externalUrl: 'https://www.ip138.com',
    alternatives: [
      { name: '站长工具 IP', url: 'https://tool.chinaz.com/ip', description: 'IP 查询' },
      { name: '站长工具 端口', url: 'https://tool.chinaz.com/port', description: '端口扫描' },
    ],
    keywords: ['ip', 'dns', '端口', '网络', '检测'],
  },
  {
    type: 'external' as const,
    id: 'api-mock',
    name: 'API Mock',
    description: '在线 Mock API 接口数据',
    icon: <Zap size={18} />,
    category: 'external' as const,
    externalUrl: 'https://designer.mocky.io',
    alternatives: [
      { name: 'FastMock', url: 'https://fastmock.site', description: 'Mock 服务' },
      { name: 'JSONPlaceholder', url: 'https://jsonplaceholder.typicode.com', description: 'Mock API' },
    ],
    keywords: ['mock', 'api', '模拟', '接口', '测试'],
  },
  {
    type: 'external' as const,
    id: 'performance-test',
    name: '性能测试',
    description: '网站性能和速度测试',
    icon: <Search size={18} />,
    category: 'external' as const,
    externalUrl: 'https://www.17ce.com',
    alternatives: [
      { name: '站长工具 测速', url: 'https://tool.chinaz.com/speed', description: '网站测速' },
      { name: 'WebPageTest', url: 'https://www.webpagetest.org', description: '网站测速' },
    ],
    keywords: ['性能', '速度', '测试', 'pagespeed', 'lighthouse'],
  },
  {
    type: 'external' as const,
    id: 'tool-lu',
    name: 'Tool.lu 工具箱',
    description: '在线综合工具集合',
    icon: <Globe size={18} />,
    category: 'external' as const,
    externalUrl: 'https://tool.lu',
    alternatives: [
      { name: '67tool', url: 'https://www.67tool.com', description: '在线工具' },
      { name: '站长工具', url: 'https://tool.chinaz.com', description: '站长工具' },
    ],
    keywords: ['工具箱', '在线工具', '综合', 'tool.lu'],
  },
];

export { internalTools, externalTools };

export function registerAllTools() {
  for (const tool of internalTools) {
    registerTool(tool);
  }
  for (const tool of externalTools) {
    registerTool(tool);
  }
}
